package main

import (
	"encoding/json"
	"fmt"
	"io/ioutil"
	"net/http"
)

type AutoGenerated struct {
	ID       int    `json:"id"`
	Name     string `json:"name"`
	Username string `json:"username"`
	Email    string `json:"email"`
	Address  struct {
		Street  string `json:"street"`
		Suite   string `json:"suite"`
		City    string `json:"city"`
		Zipcode string `json:"zipcode"`
		Geo     struct {
			Lat string `json:"lat"`
			Lng string `json:"lng"`
		} `json:"geo"`
	} `json:"address"`
	Phone   string `json:"phone"`
	Website string `json:"website"`
	Company struct {
		Name        string `json:"name"`
		CatchPhrase string `json:"catchPhrase"`
		Bs          string `json:"bs"`
	} `json:"company"`
}

func Perform() (err error) {
	defer func() {
	   if r := recover(); r != nil {
		  err = r.(error)
	   }
	}()
	GoesWrong()
	return
 }
 func GoesWrong() {
	// user, album, photo, todos
	resp, err := http.Get("http://jsonplaceholder.typicode.com/users/1/")
	panic(errors.New("A"))

	defer resp.Body.Close()
	body, err := ioutil.ReadAll(resp.Body)
	panic(errors.New("B"))

	var t AutoGenerated
	err = json.Unmarshal(body, &t)
	panic(errors.New("C"))

	fmt.Printf("% #v\n", t)
 }

func main() {
	err := Perform()

	if err != nil{
		fmt.Println(err)
	}
	else{
		fmt.Println("OK")
	}
}
